name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build Debug with Gradle
      run: ./gradlew assembleDebug --stacktrace
    - name: Build Release with Gradle
      run: ./gradlew assembleRelease --stacktrace
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: archive/app/
        signingKeyBase64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
    - name: Rename Signed APKs
      run: |
        for FILE in archive/app/*unsigned-signed.apk
        do
          mv "${FILE}" "${FILE/unsigned-signed/signed}"
        done
    - name: Upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build Artifacts
        path: |
          archive/app/*-signed.apk
          archive/app/*-mapping.txt
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          archive/app/*-signed.apk
          archive/app/*-mapping.txt